# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2f60b7b9ee5424e619a30e387af11e318f36e3a626a0a5ebaf6e655835c74bbb3edcf9caf3fd11c09d14603e425ec12017f8935dc1bb1074c4607c805ac31e40

test:
  secret_key_base: 2e3ac8b64164f82a04cad86698b32706c6c56962ba244fa88a6d7c01d3a6e5e9218457c35b81bf8b489534a0974c3b795631976f7c3ff82df5bc075449481fa6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
